# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-V-ZNIIW_2UmXwV0WW9BQe9N8zUUa4U
"""

!pip install datasets
from datasets import load_dataset
dataset= load_dataset('lukebarousse/data_jobs')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x=np.arange(0,5,0.1)
y=np.sin(x)
plt.plot(x,y)

df=dataset['train'].to_pandas() #conversion to dataframe

df.info()

#cleanup
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])

df.info()

x=np.array([1,2,3,4,5])
y=np.array([5,4,55,2,1])
plt.plot(x,y)
plt.show()

X=['mon','tue','wed','thu','fri']
Y=[10,20,47,40,5]
plt.plot(X, Y, color='PURPLE',linestyle='--',linewidth=2,marker='o',label='2025 sales')
plt.title('sales of the week')
plt.xlabel('days')
plt.ylabel('sales per day')
plt.legend(loc='upper left')
plt.grid(color='grey',linestyle='-.')
plt.xlim(1,7)
plt.ylim(0,100)
plt.xticks([1,2,3,4,5,6,7],['D1','D2','D3','D4','D5','D6','D7'])
plt.show()

import matplotlib.pyplot as plt

x = [1, 2, 3, 4]
y1 = [1, 4, 9, 16]
y2 = [1, 2, 3, 4]

plt.plot(x, y1, marker='o',label="Squared")   # yaha label diya
plt.plot(x, y2, label="Linear")    # yaha bhi label diya

plt.legend(loc="upper left")  # legend me dono label dikhenge
plt.show()

product=['a','b','c','d']
sales=[1000,1600,700,1200]
plt.bar(product,sales,color='red',width=0.2,label='product sales')
plt.title('product sales')
plt.xlabel('product')
plt.ylabel('sales')
plt.legend(loc='upper left')
plt.show()

#horizontal plt.barh
product=['a','b','c','d']
sales=[1000,1600,700,1200]
plt.barh(product,sales,color='red',label='product sales',height=0.4)
plt.title('product sales')
plt.xlabel('sales')
plt.ylabel('product')
plt.legend(loc='upper right')
plt.show()

region=['North','South','East','West']
revenue=[1800,1101,1650,4658]
plt.pie(revenue,labels=region,autopct='%1.1f%%',colors=['skyblue','magenta','beige','pink'])
plt.title('region revenue')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

data = [432,45,564,6,345,45,234,5,234,234,234,623,884,234,283,585,64,568,767,56,785,85,778,578,567,85,76,46]
plt.hist(data, bins=6, color='skyblue', edgecolor='black')


plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Simple Histogram')

plt.show()

hours_studied=[1.4,2.5,5.3,6.4,4.5,3.4,5.7,3.4]
marks=[54,76,32,88,43,24,83,77]
plt.scatter(marks,hours_studied,color='pink',marker='+',label='Student_detail')
plt.title('marks vs hours studied')
plt.xlabel('hours studied')
plt.ylabel('marks')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

hours = [1,2,3,4,5,6,7,8]
math = [35, 50, 65, 70, 75, 80, 85, 90]

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.scatter(hours, math, color='blue')
plt.title('Scatterplot')

plt.subplot(1,2,2)
plt.bar(hours, math)
plt.title('Bar Chart')


plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

hours = [1,2,3,4,5,6,7,8]
math = [35, 50, 65, 70, 75, 80, 85, 90]
fig,ax=plt.subplots(1,2,figsize=(10,5))
ax[0].scatter(hours, math, color='blue')
ax[0].set_title('Scatterplot')
ax[1].bar(hours, math,color='pink')
ax[1].set_title('Bar Chart')
ax[1].set_xlabel('sex')
ax[1].set_ylabel('age')
plt.suptitle('Scatterplot and Bar Chart')
plt.tight_layout()
plt.show()

#sharex,sharey
import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y1 = [1,4,9,16,25]
y2 = [2,3,5,7,11]

fig, ax = plt.subplots(1, 2, sharey=True, figsize=(10,6))

ax[0].plot(x, y1, color="blue")
ax[0].set_title("Square Numbers")

ax[1].plot(x, y2, color="green")
ax[1].set_title("Prime Numbers")

plt.tight_layout()
plt.show()

#savefig
x=[1,2,3,4,5]
y=[8,3,5,4,9]
plt.plot(x,y,color='blue')
plt.bar(x,y,color='yellow')
plt.savefig('plot.png',dpi=600,bbox_inches='tight')